---
 - name: Get Facts
   hosts: junos
   roles:
    - juniper.junos
   connection: local
   gather_facts: no
   
 - name:
   hosts: phpipam
   sudo: yes
   gather_facts: yes
   roles:
     #- lemp
     - phpmyadmin
     #- phpipam
    