---
mysql_port: 3306 #Default is 3306, please change it if you are using non-standard
mysql_bind_address: "127.0.0.1" #Change it to "0.0.0.0",if you want to listen everywhere
mysql_root_pass: toor #MySQL Root Password
connections: 1024 #Nginx Connection
server_name: localhost #Nginx server_name, change it to your website e.g: rbgeek.com

ubuntu_mysql_pkgs:
  - mysql-server
  - mysql-client
  - python3-mysqldb
  - libmysqlclient-dev
  - python3-pip

ubuntu_php_pkgs:
  - php7.2-fpm
  - php7.2-cgi
  - php7.2-cli
  - php7.2-curl
  - php7.2-json
  - php7.2-odbc
  - php7.2-tidy
  - php7.2-common
  - php7.2-xmlrpc
  - php7.2-gd
  - php-pear
  - php7.2-gmp
  - php7.2-dev
  - php7.2-imap
  # - php7.2-mcrypt
  - php7.2-mysqlnd

