---
- name: debconf for phpmyadmin
  debconf:
    name: phpmyadmin
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { question: 'phpmyadmin/dbconfig-install', value: 'true', vtype: 'boolean' }
    - { question: 'phpmyadmin/app-password-confirm', value: '{{mysql_root_pass}}', vtype: 'password' }
    - { question: 'phpmyadmin/mysql/admin-pass', value: '{{mysql_root_pass}}', vtype: 'password' }
    - { question: 'phpmyadmin/mysql/app-pass', value: '{{mysql_root_pass}}', vtype: 'password' }
    - { question: 'phpmyadmin/reconfigure-webserver', value: '', vtype: 'multiselect' }

- name: Install the phpmyadmin
  apt:
    name: phpmyadmin
    state: present

- name: Configure site for phpmyadmin
  file:
    path: "/var/www/html/phpmyadmin"
    src: "/usr/share/phpmyadmin"
    state: link

- name: Copy the templates to their respestive destination
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: 'root'
    group: 'root'
  with_items:
    - { src: 'virtualhost.conf.j2', dest: '/etc/nginx/sites-available/{{ server_name }}' }
  notify:
    - Restart Nginx